### ISSUE TITLE
Campos de la planilla para máquinas

### ISSUE THREAD

**Issue by Fasa20** [JTMoo/StockManagement#9]
Al importar la planilla de stock de máquinas, en la pantalla no figuran la ubicación ni el modelo, aunque selecciono dichos campos al importar la planilla. 

La marca (fabricante) y la descripción (el tipo de máquina), figuran en el mismo campo.

Puede ser un error de uso y no necesariamente de programación.

**Comment by JTMoo** [comment]
Vamos a ver juntos, creo que va a ser lo mejor. Porque no sé como estaba la selección en total o que exel usaste.

**Comment by JTMoo** [comment]
@Fasa20 ya comento en el otro issue, pero en el nuevo versión columnas vacías no molestar en la importación. Pero cuando el algoritmo encuentra una fila vacía, se pare.
